### PR TITLE
extend README on usage of registry w/ k3d on podman

### PR DESCRIPTION
**Pull request by leelavg**

### CODE REVIEW

**Comment by leelavg** [comment]
rendered markdown is at https://github.com/leelavg/k3d-registry-dockerd/tree/podman-docs

**Comment by leelavg** [comment]
Even though talk is cheap, I want to mention that I also planned to create a tool like this from some time, thanks a lot for making it happen!

This was the notes I prepared, use https://github.com/containers/image and implement some of the interfaces mentioned in https://github.com/containers/image/blob/main/types/types.go by following https://github.com/containers/image/tree/main/openshift as an example, however your implementation just gets the work done in a straight forward way.

I observed in the container logs `Not Found` statements even though everything should be there in the cache while creating a second identical cluster. Will relook at it.

**Comment by ligfx** [comment]
Thanks for the contribution @leelavg. What's the difference from running it against Docker? Is it just creating the registry ahead of time to get around the missing `bridge` network?

**Comment by leelavg** [comment]
Mostly yes, as a side effect of creating registry before creating cluster we need to supply registry details explicitly.

I also believe creating registry ahead of time helps for reusing the same for multiple clusters.

Remaining part of doc just shows how to run k3d with rootless podman.

**Comment by ligfx** [comment]
Thanks @leelavg . I'd rather stick to just the information about this project, and not duplicate k3d's instructions for running with podman (I also can't replicate it... apparently podman has issues with k3d on macOS).

Do you think an added section on "running a registry separate from a specific cluster" would be helpful? Like:

```md
Or, to use a separate-but-still-k3d-managed registry:

```sh
k3d registry create -i ligfx/k3d-registry-dockerd:v0.4 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  myregistry

configfile=$(mktemp)
cat << HERE > "$configfile"
apiVersion: k3d.io/v1alpha5
kind: Simple
registries:
  use:
    - k3d-myregistry:5000
  config: |
    mirrors:
      "*":
        endpoint:
          - "http://k3d-myregistry:5000"
HERE
k3d cluster create mytest --config "$configfile"
```.
```

**Comment by leelavg** [comment]
> I'd rather stick to just the information about this project
- ack, current PR has specific about k3d with podman and podman with the project. Yes, the former can be omitted, however the suggestion doesn't reflect the usage w/ latter, like we need to supply a flag to mention the network for podman
- Nevertheless, it's still fine not to take this PR for not adding podman, I can close it.

**Comment by ligfx** [comment]
I've added another section in the readme about running as a standalone k3d registry in 18f59ca

**Pull request closed without merging**
